# tasks relevant for creating rhui Certification authority certs
- name: prepare certs directory
  action: file
      path=${cert.files.path}
      owner=root
      group=root
      mode=0755
      state=directory   
  when_set: ${cert}
  tags:
  - rhui_certs

- name: generate CA certificate
  action: shell /usr/bin/openssl req -new -x509 -extensions v3_ca -keyout ${cert.files.key} -subj "${cert.details.subject}" -out ${cert.files.ca} -days ${cert.details.days} -passout "pass:${cert.details.password}"
      chdir=${cert.files.path}
      creates=${cert.files.path}/${cert.files.ca}
  when_set: ${cert}
  tags:
  - rhui_certs

- name: create protected password file
  action: copy
      dest=${cert.files.path}/${cert.files.password}
      owner=root
      group=root
      mode=0600
      content=${cert.details.password}
  when_set: ${cert}
  tags:
  - rhui_certs

