# tasks for deploying insances
- name: debug
  local_action: debug
      msg="$ec2"

- name: spin it up
  local_action: ec2
      count=${ec2.count}
      keypair=${ec2.keypair}
      image=${ec2.image}
      type=${ec2.instance_type}
      wait=true
      group=${ec2.security_group}
      ec2_url=${ec2.url}
      ec2_access_key=${ec2.access_key}
      ec2_secret_key=${ec2.secret_key}
  register: inst_res

- name: add instance to specified groups
  local_action: add_host hostname=${item.public_ip} groupname=${new_groups}
  with_items: ${inst_res.instances}

- name: "wait for the host's ssh port to be hot"
  local_action: wait_for host=${item.public_ip} port=22 delay=5 timeout=300
  with_items: ${isnt_res.instances}

