# this should create an instance suitable for a RHUI node deployment
# it gets executed on the localhost/master
# if ${group_name} is set, the node is added to a particular group, too
- name: create an instance
  hosts:
  - 127.0.0.1
  connection: local
  gather_facts: False

  vars_files:
  - /etc/rhui.yml
  #- amis.yml

  vars:
  - region: us-east-1
  - keypair: mkovacik-us-east-1
  - image: ami-cc5af9a5
  - security_group: mkovacik-rhui
  - instance_type: m1.medium
  - ec2_url: "https://ec2.$region.amazonaws.com"


  tasks:
  - name: spin it up
    local_action: ec2
        keypair=${keypair}
        image=${image}
        type=${instance_type}
        wait=true
        group=${security_group}
        ec2_url=${ec2_url}
        ec2_access_key=${ec2.ec2_access_key}
        ec2_secret_key=${ec2.ec2_secret_key}
    register: inst_res
    when_set: $ec2

  - name: add it to the given group
    local_action: add_host hostname=${inst_res.instances[0].public_ip} groupname=${group_name}
    when_set: $group_name

  - name: "wait for the host's ssh port to be hot"
    local_action: wait_for host=${inst_res.instances[0].public_ip} port=22 delay=5 timeout=300

