# rhui nodes certs generating
# please note this is supposed to be executed on rhua node
# after CA cert has been generated
- name: generate cds keys
  action: command /usr/bin/openssl genrsa -out ${item}.key 2048
    chdir=${cert.files.path}
    creates=${cert.files.path}/${item}.key
  async: 60
  poll: 2
  with_items: ${groups.RHUI}
  when_set: ${certs}
  tags:
  - rhui_certs

- name: generate cds csrs
  action: command /usr/bin/openssl req -new -key ${item}.key -subj "${cert.details.subject} ${item}" -out ${item}.csr
    chdir=${cert.files.path}
    creates=${cert.files.path}/${item}.csr
  with_items: ${groups.RHUI}
  when_set: ${certs}
  tags:
  - rhui_certs

- name: generate cds certs
  action: command /usr/bin/openssl x509 -days ${cert.details.days} -CA ${certs.files.ca} -CAkey ${certs.files.key} -passin "pass:${cert.details.password}" -in ${item}.csr -out ${item}.crt 
    chdir=${cert.files.path}
    creates=${cert.files.path}/${item}.crt
  with_items: ${groups.RHUI}
  when_set: ${certs}
  tags:
  - rhui_certs

