# install steps for sam
- name: disable SELinux
  action: selinux
    state=disabled
  tags:
  - sam_install
  - selinux

### TODO: figure out which method should be used

- name: execute install script
  action: shell ./install_packages && touch /tmp/sam_installed.mark
    chdir=${iso.mount_path}
    creates=/tmp/sam_installed.mark
  register: sam_install_status
  when_set: ${iso.mount_path}
  tags:
  - sam_install
  - execute_install_script

#- name: install sam
#  action: yum
#    name: ${item}
#    state=present
#    enablerepo=SAM
#  with_items:
#  - katello-headpin-all
#  - splice
#  tags:
#  - sam_install
#  - packages


- name: execute configure script
  action: shell katello-configure --deployment headpin
  when: sam_install_status.changed
  tags:
  - sam_install
  - execute_configure_script
