# install steps for sam
- name: execute install script
  action: shell /mnt/sam/install_packages && touch /tmp/sam_installed.mark
    chdir=${iso.mount_path}
    creates=/tmp/sam_installed.mark
  when_set: ${iso.mount_path}
  tags:
  - sam_install
  - execute_install_script
