- name: setup RHUI node storage
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/storage_setup.yml


- name: RHUI iso
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/rhui_iso.yml


- name: install CDS
  hosts:
  - CDS
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/cds_install.yml
  - include: common/iptables_setup.yml


- name: install RHUA
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/rhua_install.yml
  - include: common/iptables_setup.yml


- name: install PROXY
  hosts:
  - PROXY
  user: root

  vars_files:
  - common/vars/proxy.yml

  tasks:
  - include: common/proxy_install.yml
  - include: common/proxy_configure.yml



- name: generate RHUI certs
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/certs.yml

  tasks:
  - include: common/ca_cert.yml
  - include: common/rhui_cert.yml


- name: RHUI config build
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/answers.yml
  - common/vars/certs.yml
  - common/vars/storage.yml
  - common/vars/proxy.yml

  tasks:
  - include: common/answers.yml
  - include: common/rhui_manager_reset.yml


- name: Configure RHUI
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml
  - common/vars/answers.yml

  tasks:
  - include: common/rhui_config.yml

