- name: setup RHUI node storage
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/storage_setup.yml


- name: RHUI iso
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/rhui_iso.yml


- name: install CDS
  hosts:
  - CDS
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - include: common/cds_install.yml
  

- name: install RHUA packages
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/storage.yml

  tasks:
  - name: run Install_RHUA.sh
    action: shell ${rhui_iso.mount_path}/install_RHUA.sh chdir=${rhui_iso.mount_path}
    async: 600
    poll: 5
    when_set: $rhui_iso
    tags:
    - install_rhua


- name: generate RHUI certs
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/certs.yml

  tasks:
  - include: common/ca_cert.yml
  - include: common/rhui_cert.yml


- name: RHUI config build
  hosts:
  - RHUA
  user: root

  vars_files:
  - common/vars/answers.yml
  - common/vars/certs.yml
  - common/vars/storage.yml
  
  tasks:
  - include: common/answers.yml
 
 
- name: Configure RHUI
  hosts:
  - RHUI
  user: root

  vars_files:
  - common/vars/storage.yml
  - common/vars/answers.yml

  tasks:
  - include: common/rhui_config.yml
 

