# setup a SATELLITE node
- name: setup satellite node
  hosts:
  - SATELLITE
  user: root

  vars_files:
  - satellite/vars/storage.yml
  - satellite/vars/iso.yml
  - satellite/vars/rhn.yml
  - satellite/vars/answers.yml

  vars_prompt:
  - name: "rhn_user"
    prompt: "Enter RHN username"
    private: no
  - name: "rhn_password"
    prompt: "Enter RHN password"
    private: yes
  - name: "rhn_sysname"
    prompt: "Enter RHN system id"
    private: no
  
  tasks:
  # user and group for the embedded postgresql
  - name: create db group
    action: group
      name=postgres
      gid=26
      system=yes

  - name: create db user
    action: user
      name=postgres
      group=postgres
      shell=/bin/bash
      home=/var/lib/pgsql
      comment='PostgreSQL Server'
      uid=26
      createhome=no
      system=yes

  # create storage
  - include: common/storage.yml
    vars:
      storage:
        name: ${storage.satellite.name}
        mount_path: ${storage.satellite.mount_path}

  - include: common/storage.yml
    vars:
      storage:
        name: ${storage.db.name}
        mount_path: ${storage.db.mount_path}
        owner: postgres
        group: postgres
        mode: 0755
  
  # copy and mount the satellite iso
  - include: common/iso.yml

  # provide satellite install answers 
  - include: satellite/answers.yml
    vars:
      rhn:
        user: $rhn_user
        password: $rhn_password
        sysname: $rhn_sysname

  # install satellite
  - include: satellite/install.yml
