# satellite credentials to be set on Master

# copy satellite cert to master
- name: copy satellite cert
  action: copy
    src=${credentials.rhn_cert}
    dest=${credentials.rhn_cert}
    owner=${credentials.owner}
    group=${credentials.group}
    mode=${credentials.mode}
  when_set: ${credentials.rhn_cert}
  when_set: ${credentials.path}
  when_set: ${credentials.owner}
  when_set: ${credentials.group}
  when_set: ${credentials.mode}
  tags:
  - credentials
  - credentials_copy_cert

# answers.yml reuses these as variables input
- name: satellite master credentials template
  action: template
    src=satellite/templates/credentials.j2
    dest=${credentials.path}
    owner=${credentials.owner}
    group=${credentials.group}
    mode=${credentials.mode}
  when_set: ${credentials.rhn_user}
  when_set: ${credentials.rhn_password}
  when_set: ${credentials.rhn_system_name}
  when_set: ${credentials.rhn_cert}
  when_set: ${credentials.path}
  when_set: ${credentials.owner}
  when_set: ${credentials.group}
  when_set: ${credentials.mode}
  tags:
  - credentials
  - credentials_template
