# install steps for satellite
- name: remove rh-amazon-rhui-client
  action: yum
    name=rh-amazon-rhui-client
    state=absent
  tags:
  - satellite_install
  - remove_rhui_client

- name: execute the install script
  action: shell ./install.pl --skip-db-diskspace-check --answer-file=${answers.file} --non-interactive  && touch /tmp/satellite_installed.mark
    chdir=${iso.mount_path}
    creates=/tmp/satellite_installed.mark
  when_set: ${iso.mount_path}
  tags:
  - satellite_install
  - execute_install_script
    
  
