credentials:
  path: /etc/satellite-credentials.yml
  mode: 600
  owner: root
  group: root 
  rhn_user: '{{ rhn_user }}'
  rhn_password: '{{ rhn_password }}'
  rhn_system_name: '{{ rhn_system_name }}'
  rhn_cert: /tmp/satellite-cert.xml
